### PR TITLE
Adding Axelerant and MLS sponsors

### PR DESCRIPTION
**Pull request by decoupleddays**

### CODE REVIEW

**Comment by decoupleddays** [comment]
https://deploy-preview-34--decoupled-days-2018.netlify.com/

**Comment by decoupleddays** [comment]
https://deploy-preview-34--decoupled-days-2018.netlify.com/

**Comment by JeffTomlinson** [comment]
@mark-casias Can we close this PR because #35?

**Comment by decoupleddays** [comment]
Not necessary since we are now using Drupal as the source for sponsors

**Pull request closed without merging**
